# config.yaml
data:
  default_sources: ["yfinance", "alpaca"]
  default_period: "5y"
  default_currency: "USD"
  fx_provider: "yfinance"

portfolio:
  risk_free_rate: 0.02
  default_optimization: "efficient_risk"
  default_risk_tolerance: 0.10
  rebalance_frequency: "monthly"

optimization:
  genetic:
    population_size: 200
    generations: 100
    cxpb: 0.7
    mutpb: 0.2
  black_litterman:
    delta: null

risk:
  var_confidence_level: 0.95
  stress_scenarios:
    market_crash_2008:
      shock: -0.15
    rate_hike:
      sectors:
        Technology: -0.02
        Financials: 0.03

ml:
  models:
    - "LSTM"
    - "Prophet"
    - "XGBoost"
  sentiment:
    model_name: "ProsusAI/finbert"
  backtest:
    initial_capital: 100000
    commission: 0.001

compute:
  backend: "dask"
  n_workers: 4

# Словарь таксономии активов
asset_taxonomy:
  AAPL:
    sector: "Technology"
    asset_class: "Equity"
    region: "US"
  MSFT:
    sector: "Technology"
    asset_class: "Equity"
    region: "US"
  GOOG:
    sector: "Communication Services"
    asset_class: "Equity"
    region: "US"
  AMZN:
    sector: "Consumer Cyclical"
    asset_class: "Equity"
    region: "US"
  META:
    sector: "Communication Services"
    asset_class: "Equity"
    region: "US"
  SPY:
    sector: "Broad Market"
    asset_class: "ETF"
    region: "US"
  # ... добавь больше ...
